package org.example.dao;

import org.example.dataobject.BusDO;

import java.util.List;
import java.util.Map;

public interface BusDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    int insert(BusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    int insertSelective(BusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    BusDO selectByPrimaryKey(Integer id);
    BusDO selectByBusId(String BusId);
    List<Map> scanAllBus();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    int updateByPrimaryKeySelective(BusDO record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_location
     *
     * @mbg.generated Sat May 15 21:03:55 HKT 2021
     */
    int updateByPrimaryKey(BusDO record);
}